### ISSUE TITLE
NameError: name 'likelihood_type' is not defined

### ISSUE THREAD

**Issue by fengzhizhu123** [Relativist1/Gallifray#3]
I run the sample script $ python example_script.py. However, there is a nameerror mistake, i.e., "NameError: name 'likelihood_type' is not defined". Can you help me to solve this problem? Thanks.

**Comment by Relativist1** [comment]
Hi, 
The library went through some heavy changes, and the script wasn't updated.
Now it should work fine.

**Comment by fengzhizhu123** [comment]
Hi,
Thanks for your help and time.
